baseurl = ""
# baseurl = "https://felderdigital.com/projects/gargano/"
# canonifyURLs = true

title = "Gargano Reconstructive"
copyright = "&copy; 2019 Gargano Reconstructive"

[params]
  author = "Felder Digital"
  description = "NY & NJ's Premier Plastic Surgeon, Dr. Gargano provides the best expertise and care to his patients."

# Taxonomies.
[taxonomies]
  tag = "tags"
