baseurl = ""
# baseurl = "https://felderdigital.com/projects/gargano/"
# canonifyURLs = true

title = "Gargano Reconstructive"
copyright = "&copy; 2019 Gargano Reconstructive"

[params]
  author = "Felder Digital"
  description = ""

# Taxonomies.
[taxonomies]
  tag = "tags"
